import Options
from os import unlink, symlink, popen
from os.path import exists 

srcdir = "."
blddir = "build"
VERSION = "0.0.1"

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")

def build(bld):
  obj = bld.new_task_gen("cxx", "shlib", "node_addon")
  obj.target = "misc"
  obj.source = "misc.cpp"

def shutdown():
  if Options.commands['clean']:
    if exists('misc.node'): unlink('misc.node')
  else:
    if exists('build/default/misc.node') and not exists('misc.node'):
      symlink('build/default/misc.node', 'misc.node')
